### ISSUE TITLE
Avatar tekstin bitcoin muutettava isolle Blle

### ISSUE THREAD

**Issue by tlindi** [bitcoin-yhdistys/content#1]
Millä sovelluksella xcf tiedostoja voi muokata?

Avatarin fileeseen pitäisi muuttaa bitcoin B isoksi ja luoda uudet .png fileet.

**Comment by tlindi** [comment]
@satunnaisotus-juho ?

**Comment by satunnaisotus-juho** [comment]
Esim. gimpillä voi muokata .xcf-tiedostoja .

**Comment by tlindi** [comment]
PR #5 korjaa tämän.
