### ISSUE TITLE
Ehdotus

### ISSUE THREAD

**Issue by tlindi** [bitcoin-yhdistys/content#6]
"content" repon nimen muutos -> Bitcoin-yhdistys-logo

**Comment by ottomagic** [comment]
Mun mielestä ihan jees kohdentaa repo pelkästään logolle.

Laittaisin repon nimen kokonaan pienellä, koska se on yleinen käytäntö. Ei pistä samalla tavalla silmään. Repon nimi voisi mun puolesta olla myös pelkkä "logo", koska on jo bitcoin-yhdistys -organisaation alla.

Olikohan @satunnaisotus-juho visioinu jotain ylevää repoa luodessaan ja onko mielipiteitä tähän aiheeseen?

**Comment by tlindi** [comment]
> Mun mielestä ihan jees kohdentaa repo pelkästään logolle.
> 
> Laittaisin repon nimen kokonaan pienellä, koska se on yleinen käytäntö. Ei pistä samalla tavalla silmään. Repon nimi voisi mun puolesta olla myös pelkkä "logo", koska on jo bitcoin-yhdistys -organisaation alla.
> 
> Olikohan @satunnaisotus-juho visioinu jotain ylevää repoa luodessaan ja onko mielipiteitä tähän aiheeseen?

kyllä. Kaikki tuo sopii hyvin myös mulle.

**Comment by ottomagic** [comment]
Ei ole tullut vastalauseita. Laitoin Juholle toissapäivänä viestiä telegrammissa, johon ei ole vielä tullut vastausta. Uskon, että uudelleennimeäminen on myös Juholle ok. Nimeän siis repon uudelleen ja laitetaan nimeksi pelkkä "logo".

**Comment by ottomagic** [comment]
Nimetty uudelleen
